name: proper_enum_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  proper_enum:
    path: ../proper_enum

dev_dependencies:
  proper_enum_generator:
    path: ../proper_enum_generator
  build_runner: ^2.4.6

  lints: ^2.1.0
  test: ^1.24.0
