name: proper_enum_generator
description: proper_enum_generator
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  source_gen: ^1.4.0
  build: ^2.4.1
  build_config: ^1.1.1
  code_builder: ^4.8.0
  analyzer: ^6.3.0

  proper_enum:
    path: ../proper_enum

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
