name: proper_enum
description: proper_enum
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:

dev_dependencies:
  build_runner: ^2.4.6
  build_test: ^2.2.1
  build_verify: ^3.1.0
  proper_enum_generator:
    path: ../proper_enum_generator

  lints: ^2.1.0
  test: ^1.24.0
